### ISSUE TITLE
Default or initial value

### ISSUE THREAD

**Issue by tmnut** [jpederson/Accrue.js#12]
How do you setup the default value from html or php side without the library overriding these values.

The default or initial value for every page is dynamic so the static default value in the library itself can't be used.

I am not that good  in js so I can't make changes and contribute. Sorry.

Thank you.

**Comment by jpederson** [comment]
This can be passed in as options to the plugin like so:

```
$( selector ).accrue({
  default_values: {
    amount: "$7,500",
    rate: "7%",
    rate_compare: "1.49%",
    term: "36m",
  }
});
```

If you prefer to do it in the HTML, you should output your own fields onto the page and then just add the 'accrue' class to your form. You can find out more about creating your own fields in the Wiki at: https://github.com/jpederson/Accrue.js/wiki/Customizing-Fields
