### ISSUE TITLE
Read Only Field

### ISSUE THREAD

**Issue by energylevels** [jpederson/Accrue.js#19]
Is there an option to make an input field read-only? I want to make the interest field read only if possible

Thanks

**Comment by Ossuary** [comment]
I too am interested in this option. Is it doable? 
Did you find out how, @energylevels ?

Thank you

**Comment by energylevels** [comment]
I had been a bit lazy and not looked through the documentation, it says you can create you own input fields rather than letting the plugin auto-generate them, although I've not tried it yet I'm assuming you can just create you own readonly field,  like this:

```
<div class="calculator">
    <div class="form">
      <input type="text" class="amount" value="$7,500">
        <input type="text" class="rate" value="7%" readonly>
        <input type="text" class="term" value="36m">
    </div>
</div>
```
