### ISSUE TITLE
european price format

### ISSUE THREAD

**Issue by Solaris67** [jpederson/Accrue.js#30]
Hello,
us price is $7,500.50
european is 7 000,50€
To have this i add the folowing code:

`    function formatNumber (num) {
//      return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,"); // original line
		return num.toString().toFixed(2) // always two decimal digits
		return num.toString().replace(".", ",") // replace decimal point character with ,	
		return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "1");
    } `

Work good for the results but how to proceed for the fields? The fields don't accept a comma, just a dot! I would like to have a comma for the decimals...

Can you help me?
Reagards
Olivier

**Comment by jpederson** [comment]
Hello - sorry for the delay on this, just getting around to doing some refinements to this library.

I've added support for currency internationalization (any currency), so as of [v0.1.0](https://github.com/jpederson/Accrue.js/releases/tag/0.1.0), there's a new option you can set with the currency code ('EUR' in your case), and it'll format according to javascripts [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) specification.
