### ISSUE TITLE
No option to return loan amount in response_basic output

### ISSUE THREAD

**Issue by leecollings** [jpederson/Accrue.js#5]
Along with the default values allowed for response_basic output, is it possible to also include the original loan amount entered within here?

**Comment by leecollings** [comment]
// replace the placeholders with the response values.
    var output_content = options.response_basic
    .replace( "%original_amount%", get_field( elem, options, "amount" ) )
    .replace( "%payment_amount%", loan_info.payment_amount_formatted )
    .replace( "%num_payments%", loan_info.num_payments )
    .replace( "%total_payments%", loan_info.total_payments_formatted )
    .replace( "%total_interest%", loan_info.total_interest_formatted );

**Comment by jpederson** [comment]
I'll get this fixed this weekend so you can output both the formatted and raw loan totals as needed. Thanks for bringing this to my attention.
