### ISSUE TITLE
Results number rounding possible?

### ISSUE THREAD

**Issue by helmiaditya14** [jpederson/Accrue.js#6]
Is it possible to round the results (and possibly add separator) after calculation? I don't understand jquery/javascript to do such change, and I searched around the code and see no easy way to adjust it.

In my case, lets say the end result is 529211.66. Is it possible to format the results into something like 529.000?

Thanks for the great plugin!

**Comment by leecollings** [comment]
Hi, did you ever find a solution to this? I'm looking for the same function. I've got some really awful looking results for some calculations, that I want to round up to the nearest whole unit.

**Comment by jpederson** [comment]
The existing plugin provides a `$.loanInfo` helper function that returns both formatted and unformatted calculations - so you'd be able to take the unformatted number(s) and format them however you'd like or use them for other more exact calculations.

Best,
James

**Comment by samthirteen** [comment]
I added this to my success callback to remove the last 3 characters (e.g = .05). I hope it helps someone.

`$('.payment-amount').text(function (_,txt) {
    return txt.slice(0, -3);
});`
